spring.application.name=demo

# Configuración de MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://avnadmin:@mysql-215f6225-dcll-0811.d.aivencloud.com:14579/gemelasboutique?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_ac4Qt4l9l5vN96wl4Gq}

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

